name: 'Update Nix Flakes'
description: 'Automatically updates all Nix flake.lock files in your repository and creates a pull request with the updates.'
author: 'Comamoca'
runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install Nix
      uses: cachix/install-nix-action@v26
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Update all flake.nix files
      run: |
        find . -name "flake.nix" -type f | while read -r flake_file; do
          flake_dir=$(dirname "$flake_file")
          echo "Updating flake in: $flake_dir"
          (cd "$flake_dir" && nix flake update)
        done
      shell: bash
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: ':package: Update flake.lock files'
        title: 'chore: Update Nix flake dependencies'
        body: |
          Automated update of all Nix flake dependencies.\n\nAll directories containing flake.nix files have been updated.\n\n🤖 Generated with GitHub Actions
        branch: update-flakes
        base: main
        delete-branch: true
branding:
  icon: package
  color: green