name: Update Nix Flakes

on:
  schedule:
    - cron: '0 17 * * *'  # Run daily at 2 AM JST (17:00 UTC)
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-flakes:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - name: Update Nix Flakes
        uses: Comamoca/flakes-updater@1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
            
